### Collection GET
GET http://localhost:3000/v1/games
Accept : application/json
Accept-Language: fr;q=0.9,en-US;q=0.8,en;q=0.7,fr_FR

### GET en format YAML
GET http://localhost:3000/v1/games
Accept: application/x-yaml

### GET en format XML
GET http://localhost:3000/v1/games
Accept: application/xml

### GET en format JSON avec versioning V2
GET http://localhost:3000/v1/games
Accept: application/json
Accept-Language: en
X-API-Version: v2


### Collection POST
POST http://localhost:3000/v1/games
Content-Type: application/json
Accept-Language: fr;q=0.9,en-US;q=0.8,en;q=0.7,fr_FR

{
    "title": "FIFA",
    "release_date": "2015-04-06",
    "description": "Jeu de foot"
}

### Item GET en HATEOAS
GET http://localhost:3000/v1/games/4

### Item PATCH : modification partielle
PATCH http://localhost:3000/v1/games/4
Content-Type: application/json

{
    "description": "Jeu de combat",
    "publisher_id": 2
}

### Item DELETE
DELETE http://localhost:3000/v1/games/3

